# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
       Symfony\Component\Security\Core\User\User: plaintext
       FirstUsersBundle\Entity\Users: sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      main:
        entity:
          class:    FirstUsersBundle\Entity\Users
          property: username
      fos_userbundle:
        id: fos_user.user_provider.username




    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

