# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    firstusers.form.registration:
        class: FirstUsersBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: firstusers_user_registration }
        arguments: ['@?']